// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FxCurrencyConverterIntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("FxCurrencyConversion", Description="\tSimple library for currency conversion", SourceFile="Features\\FxCurrencyConversion.feature", SourceLine=0)]
    public partial class FxCurrencyConversionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "FxCurrencyConversion.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "FxCurrencyConversion", "\tSimple library for currency conversion", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When using invalid Currency pair conversion should not succeed.", SourceLine=4)]
        public virtual void WhenUsingInvalidCurrencyPairConversionShouldNotSucceed_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When using invalid Currency pair conversion should not succeed.", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrencyPair",
                            "Side",
                            "Amount",
                            "Guid"});
                table1.AddRow(new string[] {
                            "1",
                            "GBP/USA",
                            "Buy",
                            "100",
                            "d03f4ed9-179e-4390-a427-c8cb8142403f"});
                table1.AddRow(new string[] {
                            "2",
                            "GBP/",
                            "Buy",
                            "100",
                            "5bf27ab2-3ff1-4760-af7e-c666aff07a93"});
                table1.AddRow(new string[] {
                            "3",
                            "GBP/GBP",
                            "Buy",
                            "100",
                            "0f72cc92-ac01-48ab-ad7f-e25d88f8e4c3"});
                table1.AddRow(new string[] {
                            "4",
                            "XXX/YYY",
                            "Sell",
                            "100",
                            "28df2e52-7abf-41c5-8d47-e7155135a9b7"});
#line 8
 testRunner.And("our input is:", ((string)(null)), table1, "And ");
#line hidden
#line 15
 testRunner.When("we run the calculation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table2.AddRow(new string[] {
                            "1",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "GBP/USA",
                            "100",
                            "",
                            "Buy",
                            "d03f4ed9-179e-4390-a427-c8cb8142403f"});
                table2.AddRow(new string[] {
                            "2",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "GBP/",
                            "100",
                            "",
                            "Buy",
                            "5bf27ab2-3ff1-4760-af7e-c666aff07a93"});
                table2.AddRow(new string[] {
                            "3",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "GBP/GBP",
                            "100",
                            "",
                            "Buy",
                            "0f72cc92-ac01-48ab-ad7f-e25d88f8e4c3"});
                table2.AddRow(new string[] {
                            "4",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "XXX/YYY",
                            "100",
                            "",
                            "Sell",
                            "28df2e52-7abf-41c5-8d47-e7155135a9b7"});
#line 17
 testRunner.Then("the expected results should be", ((string)(null)), table2, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table3.AddRow(new string[] {
                            "1",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "GBP/USA",
                            "100",
                            "",
                            "Buy",
                            "d03f4ed9-179e-4390-a427-c8cb8142403f"});
                table3.AddRow(new string[] {
                            "2",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "GBP/",
                            "100",
                            "",
                            "Buy",
                            "5bf27ab2-3ff1-4760-af7e-c666aff07a93"});
                table3.AddRow(new string[] {
                            "3",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "GBP/GBP",
                            "100",
                            "",
                            "Buy",
                            "0f72cc92-ac01-48ab-ad7f-e25d88f8e4c3"});
                table3.AddRow(new string[] {
                            "4",
                            "ConversionFailedInvalidCcyPair",
                            "",
                            "",
                            "",
                            "XXX/YYY",
                            "100",
                            "",
                            "Sell",
                            "28df2e52-7abf-41c5-8d47-e7155135a9b7"});
#line 24
 testRunner.And("database should store", ((string)(null)), table3, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When the amount entered is invalid (zero or negative), conversion should not succ" +
            "eed.", SourceLine=33)]
        public virtual void WhenTheAmountEnteredIsInvalidZeroOrNegativeConversionShouldNotSucceed_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When the amount entered is invalid (zero or negative), conversion should not succ" +
                    "eed.", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 35
    testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrencyPair",
                            "Side",
                            "Amount",
                            "Guid"});
                table4.AddRow(new string[] {
                            "1",
                            "GBP/USD",
                            "Buy",
                            "0",
                            "9bff6400-3f38-4682-acf9-5b0b75669242"});
                table4.AddRow(new string[] {
                            "2",
                            "GBP/USD",
                            "Buy",
                            "-10",
                            "b46e6efb-5930-4b34-86d1-8011d44efded"});
#line 37
 testRunner.And("our input is:", ((string)(null)), table4, "And ");
#line hidden
#line 42
 testRunner.When("we run the calculation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table5.AddRow(new string[] {
                            "1",
                            "ConversionFailedInvalidAmount",
                            "",
                            "",
                            "",
                            "GBP/USD",
                            "0",
                            "",
                            "Buy",
                            "9bff6400-3f38-4682-acf9-5b0b75669242"});
                table5.AddRow(new string[] {
                            "2",
                            "ConversionFailedInvalidAmount",
                            "",
                            "",
                            "",
                            "GBP/USD",
                            "-10",
                            "",
                            "Buy",
                            "b46e6efb-5930-4b34-86d1-8011d44efded"});
#line 44
 testRunner.Then("the expected results should be", ((string)(null)), table5, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table6.AddRow(new string[] {
                            "1",
                            "ConversionFailedInvalidAmount",
                            "",
                            "",
                            "",
                            "GBP/USD",
                            "0",
                            "",
                            "Buy",
                            "9bff6400-3f38-4682-acf9-5b0b75669242"});
                table6.AddRow(new string[] {
                            "2",
                            "ConversionFailedInvalidAmount",
                            "",
                            "",
                            "",
                            "GBP/USD",
                            "-10",
                            "",
                            "Buy",
                            "b46e6efb-5930-4b34-86d1-8011d44efded"});
#line 49
 testRunner.And("database should store", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When the CurrencyPair entered is all lowercase or mix of uppercase and lowercase," +
            " conversion should be successful.", SourceLine=55)]
        public virtual void WhenTheCurrencyPairEnteredIsAllLowercaseOrMixOfUppercaseAndLowercaseConversionShouldBeSuccessful_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When the CurrencyPair entered is all lowercase or mix of uppercase and lowercase," +
                    " conversion should be successful.", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrencyPair",
                            "Side",
                            "Amount",
                            "Guid"});
                table7.AddRow(new string[] {
                            "1",
                            "gbp/usd",
                            "Buy",
                            "100",
                            "1dc4fa42-2b2f-4a32-9aa4-0920fe257f04"});
                table7.AddRow(new string[] {
                            "2",
                            "Gbp/usd",
                            "Buy",
                            "100",
                            "fa76ed90-4e88-4c59-88b4-cddc315185f1"});
                table7.AddRow(new string[] {
                            "3",
                            "GBP/Usd",
                            "Buy",
                            "100",
                            "216ed28e-3b3f-41e5-a4f1-9e3bba3afa1d"});
                table7.AddRow(new string[] {
                            "4",
                            "gbp/USD",
                            "Buy",
                            "100",
                            "c42bd0bb-ca71-49bb-be0c-a2d316c89399"});
#line 59
 testRunner.And("our input is:", ((string)(null)), table7, "And ");
#line hidden
#line 66
 testRunner.When("we run the calculation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table8.AddRow(new string[] {
                            "1",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "1dc4fa42-2b2f-4a32-9aa4-0920fe257f04"});
                table8.AddRow(new string[] {
                            "2",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "fa76ed90-4e88-4c59-88b4-cddc315185f1"});
                table8.AddRow(new string[] {
                            "3",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "216ed28e-3b3f-41e5-a4f1-9e3bba3afa1d"});
                table8.AddRow(new string[] {
                            "4",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "c42bd0bb-ca71-49bb-be0c-a2d316c89399"});
#line 68
 testRunner.Then("the expected results should be", ((string)(null)), table8, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table9.AddRow(new string[] {
                            "1",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "1dc4fa42-2b2f-4a32-9aa4-0920fe257f04"});
                table9.AddRow(new string[] {
                            "2",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "fa76ed90-4e88-4c59-88b4-cddc315185f1"});
                table9.AddRow(new string[] {
                            "3",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "216ed28e-3b3f-41e5-a4f1-9e3bba3afa1d"});
                table9.AddRow(new string[] {
                            "4",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "c42bd0bb-ca71-49bb-be0c-a2d316c89399"});
#line 75
 testRunner.And("database should store", ((string)(null)), table9, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When using a valid Currency pair and Market is Closed, conversion should not succ" +
            "eed", SourceLine=85)]
        public virtual void WhenUsingAValidCurrencyPairAndMarketIsClosedConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When using a valid Currency pair and Market is Closed, conversion should not succ" +
                    "eed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 87
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrencyPair",
                            "Side",
                            "Amount",
                            "Guid"});
                table10.AddRow(new string[] {
                            "1",
                            "AUD/CAD",
                            "Buy",
                            "100",
                            "07e80dc3-3141-4a9b-86da-66bb0f67643c"});
                table10.AddRow(new string[] {
                            "2",
                            "AUD/CAD",
                            "Sell",
                            "100",
                            "b2fe2d55-464a-4973-a02f-2cc66c6cbdcf"});
#line 89
 testRunner.And("our input is:", ((string)(null)), table10, "And ");
#line hidden
#line 94
 testRunner.When("we run the calculation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table11.AddRow(new string[] {
                            "1",
                            "MarketClosed",
                            "",
                            "",
                            "",
                            "AUD/CAD",
                            "100",
                            "",
                            "Buy",
                            "07e80dc3-3141-4a9b-86da-66bb0f67643c"});
                table11.AddRow(new string[] {
                            "2",
                            "MarketClosed",
                            "",
                            "",
                            "",
                            "AUD/CAD",
                            "100",
                            "",
                            "Sell",
                            "b2fe2d55-464a-4973-a02f-2cc66c6cbdcf"});
#line 96
 testRunner.Then("the expected results should be", ((string)(null)), table11, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table12.AddRow(new string[] {
                            "1",
                            "MarketClosed",
                            "",
                            "",
                            "",
                            "AUD/CAD",
                            "100",
                            "",
                            "Buy",
                            "07e80dc3-3141-4a9b-86da-66bb0f67643c"});
                table12.AddRow(new string[] {
                            "2",
                            "MarketClosed",
                            "",
                            "",
                            "",
                            "AUD/CAD",
                            "100",
                            "",
                            "Sell",
                            "b2fe2d55-464a-4973-a02f-2cc66c6cbdcf"});
#line 102
 testRunner.And("database should store", ((string)(null)), table12, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When using a valid Currency pair and Market Price is Stale, conversion should not" +
            " succeed", SourceLine=107)]
        public virtual void WhenUsingAValidCurrencyPairAndMarketPriceIsStaleConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When using a valid Currency pair and Market Price is Stale, conversion should not" +
                    " succeed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 108
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 109
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrencyPair",
                            "Side",
                            "Amount",
                            "Guid"});
                table13.AddRow(new string[] {
                            "1",
                            "AUD/USD",
                            "Buy",
                            "100",
                            "4e10981c-7aa5-4dff-b22c-98609861d2a5"});
                table13.AddRow(new string[] {
                            "2",
                            "AUD/USD",
                            "Sell",
                            "100",
                            "b048af59-3428-4db1-bb00-0a1d3c139406"});
#line 111
 testRunner.And("our input is:", ((string)(null)), table13, "And ");
#line hidden
#line 116
 testRunner.When("we run the calculation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table14.AddRow(new string[] {
                            "1",
                            "StalePrice",
                            "",
                            "",
                            "",
                            "AUD/USD",
                            "100",
                            "",
                            "Buy",
                            "4e10981c-7aa5-4dff-b22c-98609861d2a5"});
                table14.AddRow(new string[] {
                            "2",
                            "StalePrice",
                            "",
                            "",
                            "",
                            "AUD/USD",
                            "100",
                            "",
                            "Sell",
                            "b048af59-3428-4db1-bb00-0a1d3c139406"});
#line 118
 testRunner.Then("the expected results should be", ((string)(null)), table14, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table15.AddRow(new string[] {
                            "1",
                            "StalePrice",
                            "",
                            "",
                            "",
                            "AUD/USD",
                            "100",
                            "",
                            "Buy",
                            "4e10981c-7aa5-4dff-b22c-98609861d2a5"});
                table15.AddRow(new string[] {
                            "2",
                            "StalePrice",
                            "",
                            "",
                            "",
                            "AUD/USD",
                            "100",
                            "",
                            "Sell",
                            "b048af59-3428-4db1-bb00-0a1d3c139406"});
#line 124
 testRunner.And("database should store", ((string)(null)), table15, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When using a valid Currency pair, market is open and price is latest, conversion " +
            "should succeed.", SourceLine=129)]
        public virtual void WhenUsingAValidCurrencyPairMarketIsOpenAndPriceIsLatestConversionShouldSucceed_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When using a valid Currency pair, market is open and price is latest, conversion " +
                    "should succeed.", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 130
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 131
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrencyPair",
                            "Side",
                            "Amount",
                            "Guid"});
                table16.AddRow(new string[] {
                            "1",
                            "GBP/USD",
                            "Buy",
                            "100",
                            "69233754-a113-4355-a1b0-4026bbbf635a"});
                table16.AddRow(new string[] {
                            "2",
                            "GBP/USD",
                            "Sell",
                            "100",
                            "9df429e9-5d73-4330-9f14-72908db4a13a"});
#line 133
 testRunner.And("our input is:", ((string)(null)), table16, "And ");
#line hidden
#line 138
 testRunner.When("we run the calculation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table17.AddRow(new string[] {
                            "1",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "69233754-a113-4355-a1b0-4026bbbf635a"});
                table17.AddRow(new string[] {
                            "2",
                            "Successful",
                            "USD",
                            "134.126",
                            "1.34126",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Sell",
                            "9df429e9-5d73-4330-9f14-72908db4a13a"});
#line 140
 testRunner.Then("the expected results should be", ((string)(null)), table17, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "ConversionResult",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "CcyPair",
                            "OriginalAmount",
                            "OriginalAmountCcy",
                            "Side",
                            "Guid"});
                table18.AddRow(new string[] {
                            "1",
                            "Successful",
                            "USD",
                            "134.272",
                            "1.34272",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Buy",
                            "69233754-a113-4355-a1b0-4026bbbf635a"});
                table18.AddRow(new string[] {
                            "2",
                            "Successful",
                            "USD",
                            "134.126",
                            "1.34126",
                            "GBP/USD",
                            "100",
                            "GBP",
                            "Sell",
                            "9df429e9-5d73-4330-9f14-72908db4a13a"});
#line 146
 testRunner.And("database should store", ((string)(null)), table18, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
