// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UserFxCurrencyConverterIntegrationTests.UserFxCurrencyConversion
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("UserFxCurrencyConversionUserSettings", Description="\tSimple library for currency conversion based on user settings", SourceFile="UserFxCurrencyConversion\\UserFxCurrencyConversionUserSettings.feature", SourceLine=0)]
    public partial class UserFxCurrencyConversionUserSettingsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "UserFxCurrencyConversionUserSettings.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UserFxCurrencyConversion", "UserFxCurrencyConversionUserSettings", "\tSimple library for currency conversion based on user settings", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When a user with Inactive Status places a request the conversion should not succe" +
            "ed", SourceLine=4)]
        public virtual void WhenAUserWithInactiveStatusPlacesARequestTheConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a user with Inactive Status places a request the conversion should not succe" +
                    "ed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "IsActive",
                            "MinTradingAmount",
                            "MaxTradingAmount",
                            "AvailableBalance",
                            "UserCcy"});
                table65.AddRow(new string[] {
                            "1",
                            "200",
                            "false",
                            "100",
                            "10000",
                            "4000",
                            "GBP"});
#line 8
 testRunner.And("user has below settings:", ((string)(null)), table65, "And ");
#line hidden
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "CcyPair",
                            "Side",
                            "Amount"});
                table66.AddRow(new string[] {
                            "1",
                            "200",
                            "87217cb6-bad5-4759-aabd-7e72d9b41c0e",
                            "GBP/USD",
                            "Buy",
                            "100"});
#line 12
 testRunner.And("the request received is:", ((string)(null)), table66, "And ");
#line hidden
#line 16
 testRunner.When("we run the calculation with latest market price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table67.AddRow(new string[] {
                            "1",
                            "200",
                            "87217cb6-bad5-4759-aabd-7e72d9b41c0e",
                            "UserInactive",
                            "GBP/USD",
                            "100",
                            "Buy",
                            "null",
                            "",
                            "",
                            "null"});
#line 18
 testRunner.Then("the expected results should be", ((string)(null)), table67, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table68.AddRow(new string[] {
                            "1",
                            "200",
                            "87217cb6-bad5-4759-aabd-7e72d9b41c0e",
                            "UserInactive",
                            "GBP/USD",
                            "100",
                            "Buy",
                            "null",
                            "",
                            "",
                            "null"});
#line 22
 testRunner.And("database should store", ((string)(null)), table68, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When a user with incorrect Min Trading Amount places a request the conversion sho" +
            "uld not succeed", SourceLine=27)]
        public virtual void WhenAUserWithIncorrectMinTradingAmountPlacesARequestTheConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a user with incorrect Min Trading Amount places a request the conversion sho" +
                    "uld not succeed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 29
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "IsActive",
                            "MinTradingAmount",
                            "MaxTradingAmount",
                            "AvailableBalance",
                            "UserCcy"});
                table69.AddRow(new string[] {
                            "2",
                            "300",
                            "true",
                            "100",
                            "10000",
                            "4000",
                            "GBP"});
#line 31
 testRunner.And("user has below settings:", ((string)(null)), table69, "And ");
#line hidden
                TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "CcyPair",
                            "Side",
                            "Amount"});
                table70.AddRow(new string[] {
                            "2",
                            "300",
                            "3e571810-9766-406a-88b1-9ce40c5df64d",
                            "GBP/USD",
                            "Buy",
                            "10"});
#line 36
 testRunner.And("the request received is:", ((string)(null)), table70, "And ");
#line hidden
#line 42
 testRunner.When("we run the calculation with latest market price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table71.AddRow(new string[] {
                            "2",
                            "300",
                            "3e571810-9766-406a-88b1-9ce40c5df64d",
                            "ConversionFailedIncorrectMinimumTradingAmount",
                            "GBP/USD",
                            "10",
                            "Buy",
                            "null",
                            "",
                            "",
                            "null"});
#line 44
 testRunner.Then("the expected results should be", ((string)(null)), table71, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table72.AddRow(new string[] {
                            "2",
                            "300",
                            "3e571810-9766-406a-88b1-9ce40c5df64d",
                            "ConversionFailedIncorrectMinimumTradingAmount",
                            "GBP/USD",
                            "10",
                            "Buy",
                            "null",
                            "",
                            "",
                            "null"});
#line 49
 testRunner.And("database should store", ((string)(null)), table72, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When a user with incorrect Available Balance places a request the conversion shou" +
            "ld not succeed", SourceLine=54)]
        public virtual void WhenAUserWithIncorrectAvailableBalancePlacesARequestTheConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a user with incorrect Available Balance places a request the conversion shou" +
                    "ld not succeed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "IsActive",
                            "MinTradingAmount",
                            "MaxTradingAmount",
                            "AvailableBalance",
                            "UserCcy"});
                table73.AddRow(new string[] {
                            "4",
                            "500",
                            "true",
                            "100",
                            "10000",
                            "150",
                            "GBP"});
#line 58
 testRunner.And("user has below settings:", ((string)(null)), table73, "And ");
#line hidden
                TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "CcyPair",
                            "Side",
                            "Amount"});
                table74.AddRow(new string[] {
                            "4",
                            "500",
                            "58372ea6-0dc3-4252-8457-ff67f5b43049",
                            "GBP/USD",
                            "Buy",
                            "151"});
#line 63
 testRunner.And("the request received is:", ((string)(null)), table74, "And ");
#line hidden
#line 67
 testRunner.When("we run the calculation with latest market price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table75.AddRow(new string[] {
                            "4",
                            "500",
                            "58372ea6-0dc3-4252-8457-ff67f5b43049",
                            "ConversionFailedInsufficientBalance",
                            "GBP/USD",
                            "151",
                            "Buy",
                            "null",
                            "",
                            "",
                            "null"});
#line 69
 testRunner.Then("the expected results should be", ((string)(null)), table75, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table76.AddRow(new string[] {
                            "4",
                            "500",
                            "58372ea6-0dc3-4252-8457-ff67f5b43049",
                            "ConversionFailedInsufficientBalance",
                            "GBP/USD",
                            "151",
                            "Buy",
                            "null",
                            "",
                            "",
                            "null"});
#line 74
 testRunner.And("database should store", ((string)(null)), table76, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When a user with an invalid Currency places a request the conversion should not s" +
            "ucceed", SourceLine=78)]
        public virtual void WhenAUserWithAnInvalidCurrencyPlacesARequestTheConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a user with an invalid Currency places a request the conversion should not s" +
                    "ucceed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 80
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "IsActive",
                            "MinTradingAmount",
                            "MaxTradingAmount",
                            "AvailableBalance",
                            "UserCcy"});
                table77.AddRow(new string[] {
                            "5",
                            "600",
                            "true",
                            "100",
                            "10000",
                            "1550",
                            "ABC"});
#line 82
 testRunner.And("user has below settings:", ((string)(null)), table77, "And ");
#line hidden
                TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "CcyPair",
                            "Side",
                            "Amount"});
                table78.AddRow(new string[] {
                            "5",
                            "600",
                            "58372ea6-0dc3-4252-8457-ff67f5b43050",
                            "GBP/USD",
                            "Sell",
                            "1550"});
#line 86
 testRunner.And("the request received is:", ((string)(null)), table78, "And ");
#line hidden
#line 90
 testRunner.When("we run the calculation with latest market price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table79.AddRow(new string[] {
                            "5",
                            "600",
                            "58372ea6-0dc3-4252-8457-ff67f5b43050",
                            "ConversionFailedInvalidCcyPair",
                            "GBP/USD",
                            "1550",
                            "Sell",
                            "null",
                            "",
                            "",
                            "null"});
#line 92
 testRunner.Then("the expected results should be", ((string)(null)), table79, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table80.AddRow(new string[] {
                            "5",
                            "600",
                            "58372ea6-0dc3-4252-8457-ff67f5b43050",
                            "ConversionFailedInvalidCcyPair",
                            "GBP/USD",
                            "1550",
                            "Sell",
                            "null",
                            "",
                            "",
                            "null"});
#line 96
 testRunner.And("database should store", ((string)(null)), table80, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("When a user with an no Currency set,  places a request the conversion should not " +
            "succeed", SourceLine=100)]
        public virtual void WhenAUserWithAnNoCurrencySetPlacesARequestTheConversionShouldNotSucceed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a user with an no Currency set,  places a request the conversion should not " +
                    "succeed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 101
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 102
 testRunner.Given("the database is clean", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "IsActive",
                            "MinTradingAmount",
                            "MaxTradingAmount",
                            "AvailableBalance",
                            "UserCcy"});
                table81.AddRow(new string[] {
                            "6",
                            "700",
                            "true",
                            "100",
                            "10000",
                            "1550",
                            ""});
#line 104
 testRunner.And("user has below settings:", ((string)(null)), table81, "And ");
#line hidden
                TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "CcyPair",
                            "Side",
                            "Amount"});
                table82.AddRow(new string[] {
                            "6",
                            "700",
                            "58372ea6-0dc3-4252-8457-ff67f5b43050",
                            "GBP/USD",
                            "Sell",
                            "1550"});
#line 108
 testRunner.And("the request received is:", ((string)(null)), table82, "And ");
#line hidden
#line 112
 testRunner.When("we run the calculation with latest market price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table83.AddRow(new string[] {
                            "5",
                            "600",
                            "58372ea6-0dc3-4252-8457-ff67f5b43050",
                            "ConversionFailedInvalidCcyPair",
                            "GBP/USD",
                            "1550",
                            "Sell",
                            "null",
                            "",
                            "",
                            "null"});
#line 114
 testRunner.Then("the expected results should be", ((string)(null)), table83, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "UserId",
                            "RequestId",
                            "ConversionResult",
                            "CcyPair",
                            "OriginalAmount",
                            "Side",
                            "ConvertedAmountCurrency",
                            "ConvertedAmount",
                            "PxUsed",
                            "OriginalAmountCcy"});
                table84.AddRow(new string[] {
                            "5",
                            "600",
                            "58372ea6-0dc3-4252-8457-ff67f5b43050",
                            "ConversionFailedInvalidCcyPair",
                            "GBP/USD",
                            "1550",
                            "Sell",
                            "null",
                            "",
                            "",
                            "null"});
#line 118
 testRunner.And("database should store", ((string)(null)), table84, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
